import { Food } from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';

export const sample_foods: Food[] = [
  {
    id: "1",
    name: "Pepperoni Pizza",
    cookTime: "20-30",
    price: 25,
    favorite: false,
    origins: ["Italy"],
    stars: 4.5,
    imageUrl: "assets/food-1.jpg",
    tags: ["Fast Food", "Pizza"],
  },
  {
    id: "2",
    name: "Meatballs",
    price: 30,
    cookTime: "30-40",
    favorite: true,
    origins: ["Italy"],
    stars: 4.7,
    imageUrl: "assets/food-2.jpg",
    tags: [],
  },
  {
    id: "3",
    name: "Hamburger",
    price: 10,
    cookTime: "10-15",
    favorite: false,
    origins: ["Germany", "USA"],
    stars: 3.5,
    imageUrl: "assets/food-3.jpg",
    tags: ["Fast Food", "Hamburger"],
  },
  {
    id: "4",
    name: "Fries",
    price: 5,
    cookTime: "15-20",
    favorite: true,
    origins: ["Belgium", "France"],
    stars: 3.3,
    imageUrl: "assets/food-4.jpg",
    tags: ["Fast Food", "Fries"],
  },
  {
    id: "5",
    name: "Chicken Soup",
    price: 15,
    cookTime: "40-50",
    favorite: false,
    origins: ["USA", "China"],
    stars: 3.0,
    imageUrl: "assets/food-5.jpg",
    tags: ["Soup"],
  },
  {
    id: "6",
    name: "Vegetarian Pizza",
    price: 20,
    cookTime: "20-30",
    favorite: false,
    origins: ["Italy"],
    stars: 4.0,
    imageUrl: "assets/food-6.jpg",
    tags: ["Fast Food", "Pizza"],
  },
];

export const sample_tags: Tag[] = [
  { name: 'All', count: 6 },
  { name: 'Fast Food', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fries', count: 1 },
  { name: 'Soup', count: 1 },
];
